version: '3.8'

services:
  web:
    build: .
    command: gunicorn sw_project.wsgi:application --bind 0.0.0.0:8000 --log-level debug --workers=${NUMBER_OF_WORKERS:-4}
    volumes:
      - static_volume:/home/app/web/staticfiles
      - tmp_volume:/home/app/web/tmp
      - writable_volume:/home/app/web/writable/media
    expose:
      - 8000
    env_file:
      - ./.env_docker
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - postgres_dumps:/postgres_dumps
    environment:
      - POSTGRES_USER=django_app_pg_user
      - POSTGRES_PASSWORD=django_app_pg_password
      - POSTGRES_DB=django_app_pg_dbname
    restart: unless-stopped
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - writable_volume:/home/app/web/writable/media
    ports:
      - 80:80
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  postgres_dumps:
  static_volume:
  tmp_volume:
  writable_volume:
