version: '3.8'

services:
  web:
    build: .
    command: gunicorn sw_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env_docker
    depends_on:
      - postgres
    restart: unless-stopped
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_app_pg_user
      - POSTGRES_PASSWORD=django_app_pg_password
      - POSTGRES_DB=django_app_pg_dbname
    restart: unless-stopped
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
