from django.contrib import admin
from .models import (Country, Place, Person, PersonViafOrCerl, Role, PersonRole, Profession, PersonProfession, Religion,
                     PersonReligion, Marriage, Child, AlternativeName, PeriodOfResidence, TypeOfCollective, Collective,
                     PersonCollective, CollectivePlace, Genre, Language, Work, WorkLanguage, PersonWork, Edition,
                     PersonEdition)

admin.site.register(Country)
admin.site.register(Place)
admin.site.register(Person)
admin.site.register(PersonViafOrCerl)
admin.site.register(Role)
admin.site.register(PersonRole)
admin.site.register(Profession)
admin.site.register(PersonProfession)
admin.site.register(Religion)
admin.site.register(PersonReligion)
admin.site.register(Marriage)
admin.site.register(Child)
admin.site.register(AlternativeName)
admin.site.register(PeriodOfResidence)
admin.site.register(TypeOfCollective)
admin.site.register(Collective)
admin.site.register(PersonCollective)
admin.site.register(CollectivePlace)
admin.site.register(Genre)
admin.site.register(Language)
admin.site.register(Work)
admin.site.register(WorkLanguage)
admin.site.register(PersonWork)
admin.site.register(Edition)
admin.site.register(PersonEdition)
