# Generated by Django 4.2.5 on 2023-09-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collective',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('dates_of_activity', models.CharField(max_length=32)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publication_year', models.IntegerField(max_length=4)),
                ('language', models.CharField(max_length=255)),
                ('person_role', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('cerl_publisher', models.IntegerField(max_length=32)),
                ('url', models.CharField(max_length=255)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.collective')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=255)),
                ('viaf_or_cerl_identifier', models.IntegerField(max_length=32)),
                ('first_name', models.CharField(max_length=255)),
                ('maiden_name', models.CharField(max_length=255)),
                ('married_name', models.CharField(blank=True, max_length=255)),
                ('alternative_name', models.CharField(blank=True, max_length=255)),
                ('date_in_use_of_name', models.DateField(blank=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('alternative_birth_date', models.DateField(blank=True)),
                ('alternative_death_date', models.DateField(blank=True)),
                ('flourishing', models.CharField(max_length=32)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unknown')], max_length=1)),
                ('alternative_name_gender', models.CharField(blank=True, max_length=255)),
                ('professional_ecclesiastic_title', models.CharField(blank=True, max_length=255)),
                ('aristocratic_title', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('date_of_role', models.CharField(max_length=32)),
                ('place_of_residence', models.CharField(max_length=255)),
                ('date_of_residence', models.CharField(max_length=32)),
                ('education', models.CharField(max_length=255)),
                ('marital_status', models.CharField(choices=[('U', 'Unmarried'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1)),
                ('date_of_marital_status', models.CharField(max_length=32)),
                ('profession', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('bibliography', models.TextField()),
                ('notes', models.TextField()),
                ('children', models.ManyToManyField(to='shewrote.person')),
                ('is_member_of', models.ManyToManyField(through='shewrote.Membership', to='shewrote.collective')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_city', models.CharField(max_length=255)),
                ('cerl_id', models.IntegerField(max_length=32)),
                ('modern_country', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedPersonWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('viaf_work', models.IntegerField(max_length=32)),
                ('language', models.CharField(max_length=255)),
                ('person_role', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('has_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.edition')),
                ('related_persons', models.ManyToManyField(through='shewrote.RelatedPersonWork', to='shewrote.person')),
            ],
        ),
        migrations.AddField(
            model_name='relatedpersonwork',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.work'),
        ),
        migrations.CreateModel(
            name='RelatedPersonEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.edition')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.work')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='place_of_birth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shewrote.place'),
        ),
        migrations.AddField(
            model_name='person',
            name='place_of_death',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shewrote.place'),
        ),
        migrations.AddField(
            model_name='person',
            name='publications',
            field=models.ManyToManyField(through='shewrote.Publication', to='shewrote.work'),
        ),
        migrations.AddField(
            model_name='person',
            name='related_to',
            field=models.ManyToManyField(to='shewrote.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='spouse',
            field=models.ManyToManyField(to='shewrote.person'),
        ),
        migrations.AddField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person'),
        ),
        migrations.AddField(
            model_name='edition',
            name='place_of_publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.place'),
        ),
        migrations.AddField(
            model_name='edition',
            name='related_persons',
            field=models.ManyToManyField(through='shewrote.RelatedPersonEdition', to='shewrote.person'),
        ),
        migrations.AddField(
            model_name='collective',
            name='has_members',
            field=models.ManyToManyField(through='shewrote.Membership', to='shewrote.person'),
        ),
        migrations.AddField(
            model_name='collective',
            name='place',
            field=models.ManyToManyField(to='shewrote.place'),
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.work')),
            ],
        ),
    ]
