# Generated by Django 4.2.5 on 2023-12-04 11:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('original_data', models.JSONField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modern_country', models.CharField(max_length=255)),
                ('alternative_country_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('cerl_publisher', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('original_data', models.JSONField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=255)),
                ('viaf_or_cerl', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('maiden_name', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.CharField(blank=True, max_length=50)),
                ('date_of_death', models.CharField(blank=True, max_length=50)),
                ('alternative_birth_date', models.CharField(blank=True, max_length=50)),
                ('alternative_death_date', models.CharField(blank=True, max_length=50)),
                ('flourishing_start', models.IntegerField(blank=True, null=True)),
                ('flourishing_end', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('N', 'Not Applicable')], max_length=1)),
                ('alternative_name_gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('N', 'Not Applicable')], max_length=1)),
                ('professional_ecclesiastic_title', models.CharField(blank=True, max_length=255)),
                ('aristocratic_title', models.CharField(blank=True, max_length=255)),
                ('bibliography', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('original_data', models.JSONField(blank=True, editable=False, null=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shewrote.person')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shewrote.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonReceptionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonReceptionSourceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonWorkRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('cerl_id', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('original_data', models.JSONField(blank=True, editable=False, null=True)),
                ('modern_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.country')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True)),
                ('reference', models.TextField(blank=True)),
                ('date_of_reception', models.IntegerField(blank=True)),
                ('quotation_reception', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('viaf_work', models.URLField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('original_data', models.JSONField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfCollective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_of_collective', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_of_document', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfReception',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_of_reception', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('viaf_work', models.URLField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('original_data', models.JSONField(blank=True, editable=False, null=True)),
                ('related_persons', models.ManyToManyField(blank=True, through='shewrote.PersonWorkRole', to='shewrote.person')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.reception')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.typeofreception')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_work', models.CharField(blank=True, max_length=255)),
                ('shelfmark', models.CharField(blank=True, max_length=255)),
                ('reference', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('original_Data', models.JSONField(blank=True, editable=False, null=True)),
                ('part_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shewrote.work')),
                ('related_persons', models.ManyToManyField(blank=True, through='shewrote.PersonReceptionSourceRole', to='shewrote.person')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shewrote.work')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.language')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.reception')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.genre')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.reception')),
            ],
        ),
        migrations.AddField(
            model_name='reception',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.typeofdocument'),
        ),
        migrations.AddField(
            model_name='reception',
            name='language_of_reception',
            field=models.ManyToManyField(blank=True, through='shewrote.ReceptionLanguage', to='shewrote.language'),
        ),
        migrations.AddField(
            model_name='reception',
            name='part_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.work'),
        ),
        migrations.AddField(
            model_name='reception',
            name='person',
            field=models.ManyToManyField(through='shewrote.PersonReceptionRole', to='shewrote.person'),
        ),
        migrations.AddField(
            model_name='reception',
            name='place_of_reception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.place'),
        ),
        migrations.AddField(
            model_name='reception',
            name='reception_genre',
            field=models.ManyToManyField(blank=True, through='shewrote.ReceptionGenre', to='shewrote.genre'),
        ),
        migrations.AddField(
            model_name='reception',
            name='reception_type',
            field=models.ManyToManyField(blank=True, through='shewrote.ReceptionType', to='shewrote.typeofreception'),
        ),
        migrations.AddField(
            model_name='reception',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.receptionsource'),
        ),
        migrations.AddField(
            model_name='personworkrole',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.role'),
        ),
        migrations.AddField(
            model_name='personworkrole',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.work'),
        ),
        migrations.CreateModel(
            name='PersonReligion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
                ('religion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.religion')),
            ],
        ),
        migrations.AddField(
            model_name='personreceptionsourcerole',
            name='reception_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.receptionsource'),
        ),
        migrations.AddField(
            model_name='personreceptionsourcerole',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.role'),
        ),
        migrations.AddField(
            model_name='personreceptionrole',
            name='reception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.reception'),
        ),
        migrations.AddField(
            model_name='personreceptionrole',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.role'),
        ),
        migrations.CreateModel(
            name='PersonProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.profession')),
            ],
        ),
        migrations.CreateModel(
            name='PersonEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.education')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonEditionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.edition')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.role')),
            ],
        ),
        migrations.CreateModel(
            name='PersonCollective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.collective')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='place_of_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shewrote.place'),
        ),
        migrations.AddField(
            model_name='person',
            name='place_of_death',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shewrote.place'),
        ),
        migrations.AddField(
            model_name='person',
            name='related_to',
            field=models.ManyToManyField(blank=True, to='shewrote.person'),
        ),
        migrations.CreateModel(
            name='PeriodOfResidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.place')),
            ],
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('married_name', models.CharField(blank=True, max_length=255)),
                ('marital_status', models.CharField(blank=True, choices=[('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shewrote.person')),
                ('spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.person')),
            ],
        ),
        migrations.CreateModel(
            name='EditionLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.edition')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.language')),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.genre'),
        ),
        migrations.AddField(
            model_name='edition',
            name='language',
            field=models.ManyToManyField(blank=True, through='shewrote.EditionLanguage', to='shewrote.language'),
        ),
        migrations.AddField(
            model_name='edition',
            name='place_of_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.place'),
        ),
        migrations.AddField(
            model_name='edition',
            name='related_persons',
            field=models.ManyToManyField(blank=True, through='shewrote.PersonEditionRole', to='shewrote.person'),
        ),
        migrations.AddField(
            model_name='edition',
            name='related_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.work'),
        ),
        migrations.CreateModel(
            name='CollectivePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.collective')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.place')),
            ],
        ),
        migrations.AddField(
            model_name='collective',
            name='has_members',
            field=models.ManyToManyField(blank=True, through='shewrote.PersonCollective', to='shewrote.person'),
        ),
        migrations.AddField(
            model_name='collective',
            name='place',
            field=models.ManyToManyField(blank=True, through='shewrote.CollectivePlace', to='shewrote.place'),
        ),
        migrations.AddField(
            model_name='collective',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.typeofcollective'),
        ),
        migrations.CreateModel(
            name='AlternativeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_name', models.CharField(max_length=255)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
            ],
        ),
    ]
