# Generated by Django 4.2.5 on 2023-09-21 10:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_year', models.IntegerField(blank=True)),
                ('end_year', models.IntegerField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('original_data', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modern_country', models.CharField(max_length=255)),
                ('alternative_country_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publication_year', models.IntegerField(blank=True)),
                ('cerl_publisher', models.CharField(blank=True, max_length=255)),
                ('person_role', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('original_data', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('maiden_name', models.CharField(blank=True, max_length=255)),
                ('married_name', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True)),
                ('date_of_death', models.DateField(blank=True)),
                ('alternative_birth_date', models.DateField(blank=True)),
                ('alternative_death_date', models.DateField(blank=True)),
                ('flourishing_start', models.IntegerField(blank=True)),
                ('flourishing_end', models.IntegerField(blank=True)),
                ('sex', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('N', 'Not Applicable')], max_length=1)),
                ('alternative_name_gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('N', 'Not Applicable')], max_length=1)),
                ('professional_ecclesiastic_title', models.CharField(blank=True, max_length=255)),
                ('aristocratic_title', models.CharField(blank=True, max_length=255)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('bibliography', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('original_data', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfCollective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_collective', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('viaf_work', models.IntegerField(blank=True)),
                ('person_role', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('original_data', models.JSONField(blank=True)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.genre')),
            ],
        ),
        migrations.CreateModel(
            name='WorkLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.language')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.work')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='language',
            field=models.ManyToManyField(blank=True, through='shewrote.WorkLanguage', to='shewrote.language'),
        ),
        migrations.AddField(
            model_name='work',
            name='related_persons',
            field=models.ManyToManyField(blank=True, through='shewrote.PersonWork', to='shewrote.person'),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_of_city', models.CharField(blank=True, max_length=255)),
                ('cerl_id', models.IntegerField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('original_data', models.JSONField(blank=True)),
                ('modern_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.country')),
            ],
        ),
        migrations.AddField(
            model_name='personwork',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.work'),
        ),
        migrations.CreateModel(
            name='PersonViafOrCerl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viaf', models.CharField(blank=True, max_length=255)),
                ('cerl', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(blank=True)),
                ('end_year', models.IntegerField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.role')),
            ],
        ),
        migrations.CreateModel(
            name='PersonReligion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(blank=True)),
                ('end_year', models.IntegerField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
                ('religion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.religion')),
            ],
        ),
        migrations.CreateModel(
            name='PersonProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(blank=True)),
                ('end_year', models.IntegerField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.profession')),
            ],
        ),
        migrations.CreateModel(
            name='PersonEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.edition')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonCollective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.collective')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='place_of_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shewrote.place'),
        ),
        migrations.AddField(
            model_name='person',
            name='place_of_death',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shewrote.place'),
        ),
        migrations.AddField(
            model_name='person',
            name='related_to',
            field=models.ManyToManyField(blank=True, to='shewrote.person'),
        ),
        migrations.CreateModel(
            name='PeriodOfResidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(blank=True)),
                ('end_year', models.IntegerField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.place')),
            ],
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(blank=True, choices=[('U', 'Unmarried'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1)),
                ('start_year', models.IntegerField(blank=True)),
                ('end_year', models.IntegerField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shewrote.person')),
                ('spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.person')),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.genre'),
        ),
        migrations.AddField(
            model_name='edition',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.language'),
        ),
        migrations.AddField(
            model_name='edition',
            name='place_of_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.place'),
        ),
        migrations.AddField(
            model_name='edition',
            name='related_persons',
            field=models.ManyToManyField(blank=True, through='shewrote.PersonEdition', to='shewrote.person'),
        ),
        migrations.AddField(
            model_name='edition',
            name='related_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.work'),
        ),
        migrations.CreateModel(
            name='CollectivePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.collective')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.place')),
            ],
        ),
        migrations.AddField(
            model_name='collective',
            name='has_members',
            field=models.ManyToManyField(blank=True, through='shewrote.PersonCollective', to='shewrote.person'),
        ),
        migrations.AddField(
            model_name='collective',
            name='place',
            field=models.ManyToManyField(blank=True, through='shewrote.CollectivePlace', to='shewrote.place'),
        ),
        migrations.AddField(
            model_name='collective',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.typeofcollective'),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shewrote.person')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shewrote.person')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shewrote.person')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_name', models.CharField(max_length=255)),
                ('start_year', models.IntegerField(blank=True)),
                ('end_year', models.IntegerField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
            ],
        ),
    ]
