# Generated by Django 4.2.5 on 2023-09-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='cerl_publisher',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='edition',
            name='publication_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='viaf_or_cerl_identifier',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='cerl_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='viaf_work',
            field=models.IntegerField(),
        ),
    ]
