# Generated by Django 4.2.5 on 2024-01-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0002_alter_place_latitude_alter_place_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='flourishing_end',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='flourishing_start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
