# Generated by Django 4.2.5 on 2024-01-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0003_alter_person_flourishing_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodofresidence',
            options={'verbose_name_plural': 'periods of residence'},
        ),
    ]
