# Generated by Django 4.2.5 on 2024-03-20 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0005_person_place_of_residence_notes'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Old table name from checking with sqlmigrate, new table
                # name from AuthorBook._meta.db_table.
                migrations.RunSQL(
                    sql="ALTER TABLE shewrote_person_related_to RENAME TO shewrote_personpersonrelation",
                    reverse_sql="ALTER TABLE shewrote_personpersonrelation RENAME TO shewrote_person_related_to",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='PersonPersonRelation',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_relations', to='shewrote.person')),
                        ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_relations', to='shewrote.person')),
                    ],
                    options={
                        'unique_together': {('from_person', 'to_person')},
                    },
                ),
                migrations.AlterField(
                    model_name='person',
                    name='related_to',
                    field=models.ManyToManyField(blank=True, through='shewrote.PersonPersonRelation', to='shewrote.person'),
                ),
            ],
        ),
    ]
