# Generated by Django 4.2.5 on 2024-05-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0005_person_place_of_residence_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonReceptionRole',
            new_name='PersonReception',
        ),
    ]
