# Generated by Django 4.2.5 on 2024-05-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0006_rename_personreceptionrole_personreception'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonWorkRole',
            new_name='PersonWork',
        ),
    ]
