# Generated by Django 4.2.5 on 2024-05-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0007_rename_personworkrole_personwork'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonEditionRole',
            new_name='PersonEdition',
        ),
    ]
