# Generated by Django 4.2.5 on 2024-05-30 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0008_rename_personeditionrole_personedition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonReceptionSourceRole',
            new_name='PersonReceptionSource',
        ),
    ]
