# Generated by Django 4.2.5 on 2024-05-30 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0009_rename_personreceptionsourcerole_personreceptionsource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeOfCollective',
            new_name='CollectiveType',
        ),
    ]
