# Generated by Django 4.2.5 on 2024-05-30 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0011_rename_typeofdocument_documenttype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReceptionType',
            new_name='ReceptionReceptionType',
        ),
    ]
