# Generated by Django 4.2.5 on 2024-05-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0012_rename_receptiontype_receptionreceptiontype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeOfReception',
            new_name='ReceptionType',
        ),
    ]
