# Generated by Django 4.2.5 on 2024-06-03 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0013_rename_typeofreception_receptiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='part_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shewrote.work'),
        ),
        migrations.CreateModel(
            name='WorkReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.reception')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.work')),
            ],
        ),
        migrations.CreateModel(
            name='EditionReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.edition')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.reception')),
            ],
        ),
        migrations.AddField(
            model_name='reception',
            name='edition',
            field=models.ManyToManyField(through='shewrote.EditionReception', to='shewrote.edition'),
        ),
        migrations.AddField(
            model_name='reception',
            name='work',
            field=models.ManyToManyField(through='shewrote.WorkReception', to='shewrote.work'),
        ),
    ]
