# Generated by Django 4.2.5 on 2024-06-03 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0014_alter_reception_part_of_work_workreception_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reception',
            old_name='edition',
            new_name='received_editions',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='person',
            new_name='received_persons',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='work',
            new_name='received_works',
        ),
        migrations.AddField(
            model_name='editionreception',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.receptiontype'),
        ),
        migrations.AddField(
            model_name='workreception',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.receptiontype'),
        ),
    ]
