# Generated by Django 4.2.5 on 2024-06-06 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0015_rename_edition_reception_received_editions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personreception',
            name='role',
        ),
        migrations.AddField(
            model_name='personreception',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.receptiontype'),
        ),
    ]
