# Generated by Django 4.2.5 on 2024-06-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0016_remove_personreception_role_personreception_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reception'),
        ),
    ]
