# Generated by Django 4.2.5 on 2024-06-26 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0019_add_indexes_to_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='date_of_reception',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reception',
            name='part_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shewrote.work', verbose_name='is same as work'),
        ),
    ]
