# Generated by Django 4.2.5 on 2024-07-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0020_alter_reception_date_of_reception_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='reception_type',
        ),
        migrations.DeleteModel(
            name='ReceptionReceptionType',
        ),
    ]
