# Generated by Django 4.2.5 on 2024-08-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0021_remove_reception_reception_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='maiden_name',
            new_name='birth_name',
        ),
    ]
