# Generated by Django 4.2.5 on 2024-08-28 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0023_personpersonrelation_alter_person_related_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True)),
                ('reverse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.relationtype')),
            ],
        ),
        migrations.AddField(
            model_name='personpersonrelation',
            name='types',
            field=models.ManyToManyField(to='shewrote.relationtype'),
        ),
    ]
