# Generated by Django 4.2.5 on 2024-09-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0024_relationtype_personpersonrelation_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpersonrelation',
            name='types',
            field=models.ManyToManyField(blank=True, to='shewrote.relationtype'),
        ),
    ]
