# Generated by Django 4.2.5 on 2024-10-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0025_alter_personpersonrelation_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='normalised_date_of_birth',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='normalised_date_of_death',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
    ]
