# Generated by Django 4.2.5 on 2024-10-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0026_person_normalised_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['normalised_date_of_birth'], name='shewrote_pe_normali_6b613d_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['normalised_date_of_death'], name='shewrote_pe_normali_9416bc_idx'),
        ),
    ]
