# Generated by Django 4.2.5 on 2024-11-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0027_person_shewrote_pe_normali_6b613d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.language')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.work')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='languages',
            field=models.ManyToManyField(blank=True, through='shewrote.WorkLanguage', to='shewrote.language'),
        ),
    ]
