# Generated by Django 4.2.5 on 2024-12-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0028_worklanguage_work_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reception',
            old_name='part_of_work',
            new_name='is_same_as_work',
        ),
    ]
