# Generated by Django 4.2.5 on 2024-12-02 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0029_rename_part_of_work_reception_is_same_as_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='part_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shewrote.work'),
        ),
    ]
