# Generated by Django 4.2.5 on 2024-12-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0028_alter_marriage_marital_status'),
        ('shewrote', '0030_reception_part_of_work'),
    ]

    operations = [
    ]
