# Generated by Django 4.2.5 on 2024-12-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0030_reception_part_of_work'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reception',
            index=models.Index(fields=['title'], name='shewrote_re_title_877094_idx'),
        ),
        migrations.AddIndex(
            model_name='reception',
            index=models.Index(fields=['date_of_reception'], name='shewrote_re_date_of_82bd25_idx'),
        ),
    ]
