# Generated by Django 4.2.5 on 2024-12-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0031_merge_20241202_1331'),
        ('shewrote', '0031_reception_shewrote_re_title_877094_idx_and_more'),
    ]

    operations = [
    ]
