# Generated by Django 4.2.5 on 2024-12-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0032_merge_20241204_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collective',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='collectivetype',
            options={'ordering': ['type_of_collective']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['modern_country'], 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['type_of_document']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['short_name']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='reception',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='receptionsource',
            options={'ordering': ['title_work']},
        ),
        migrations.AlterModelOptions(
            name='receptiontype',
            options={'ordering': ['type_of_reception']},
        ),
        migrations.AlterModelOptions(
            name='relationtype',
            options={'ordering': ['text']},
        ),
        migrations.AlterModelOptions(
            name='religion',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['title']},
        ),
    ]
