# Generated by Django 4.2.5 on 2025-01-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0033_alter_collective_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='modern_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='places', to='shewrote.country'),
        ),
    ]
