# Generated by Django 4.2.5 on 2024-12-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0033_alter_collective_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='relation_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
