# Generated by Django 4.2.5 on 2025-01-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0034_alter_place_modern_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='place_of_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birthplace_of', to='shewrote.place'),
        ),
    ]
