# Generated by Django 4.2.5 on 2024-12-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0034_person_relation_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='work_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
