# Generated by Django 4.2.5 on 2024-12-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0035_person_work_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='edition_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
