# Generated by Django 4.2.5 on 2025-01-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0035_alter_person_place_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='place_of_death',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deathplace_of', to='shewrote.place'),
        ),
    ]
