# Generated by Django 4.2.5 on 2024-12-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0036_person_edition_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='reception_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
