# Generated by Django 4.2.5 on 2024-12-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0037_person_reception_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='work_reception_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
