# Generated by Django 4.2.5 on 2025-01-27 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0037_alter_person_father_alter_person_mother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collective',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collectives', to='shewrote.collectivetype'),
        ),
    ]
