# Generated by Django 4.2.5 on 2025-01-27 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0038_alter_collective_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personwork',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shewrote.role'),
        ),
    ]
