# Generated by Django 4.2.5 on 2025-01-27 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0039_alter_personwork_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personeducation',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shewrote.education'),
        ),
        migrations.AlterField(
            model_name='personprofession',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shewrote.profession'),
        ),
        migrations.AlterField(
            model_name='personreligion',
            name='religion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shewrote.religion'),
        ),
    ]
