# Generated by Django 4.2.5 on 2025-01-29 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0040_alter_personeducation_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodofresidence',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shewrote.place'),
        ),
    ]
