# Generated by Django 4.2.5 on 2025-02-06 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0041_alter_periodofresidence_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiveplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shewrote.place'),
        ),
    ]
