# Generated by Django 4.2.5 on 2025-02-06 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0042_alter_collectiveplace_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcollective',
            name='collective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shewrote.collective'),
        ),
    ]
