# Generated by Django 4.2.5 on 2025-02-06 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0043_alter_personcollective_collective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklanguage',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shewrote.language'),
        ),
    ]
