# Generated by Django 4.2.5 on 2025-02-10 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0044_alter_worklanguage_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='related_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shewrote.work'),
        ),
    ]
