# Generated by Django 4.2.5 on 2025-02-10 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0046_alter_reception_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptiongenre',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shewrote.genre'),
        ),
    ]
