# Generated by Django 4.2.5 on 2025-02-17 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0047_alter_receptiongenre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shewrote.genre'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='place_of_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shewrote.place'),
        ),
    ]
