# Generated by Django 4.2.5 on 2025-02-17 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0048_alter_edition_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editionlanguage',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shewrote.language'),
        ),
    ]
