# Generated by Django 4.2.5 on 2025-02-18 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0049_alter_editionlanguage_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personedition',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shewrote.role'),
        ),
    ]
