# Generated by Django 4.2.5 on 2025-02-18 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0051_alter_personreceptionsource_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editionreception',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shewrote.receptiontype'),
        ),
        migrations.AlterField(
            model_name='personreception',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shewrote.receptiontype'),
        ),
        migrations.AlterField(
            model_name='workreception',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shewrote.receptiontype'),
        ),
    ]
