# Generated by Django 4.2.5 on 2025-04-15 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0053_alter_receptionlanguage_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionsource',
            name='part_of',
        ),
        migrations.RemoveField(
            model_name='receptionsource',
            name='related_persons',
        ),
        migrations.RemoveField(
            model_name='receptionsource',
            name='work',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='source',
        ),
        migrations.DeleteModel(
            name='PersonReceptionSource',
        ),
        migrations.DeleteModel(
            name='ReceptionSource',
        ),
    ]
