# Generated by Django 4.2.5 on 2025-04-17 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0054_remove_receptionsource_part_of_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='is_same_as_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_same_as_reception', to='shewrote.work', verbose_name='is same as work'),
        ),
    ]
