# Generated by Django 4.2.5 on 2025-05-12 08:55

from django.db import migrations, models
import django.db.models.deletion
import shewrote.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0055_alter_reception_is_same_as_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True)),
                ('reference', models.TextField(blank=True)),
                ('date_of_reception', models.IntegerField(blank=True, null=True)),
                ('quotation_reception', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('viaf_work', models.URLField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reception')),
                ('original_data', models.JSONField(blank=True, editable=False, null=True)),
                ('shelf_mark', models.TextField(blank=True)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shewrote.documenttype')),
                ('part_of_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shewrote.work')),
                ('place_of_reception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shewrote.place')),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
            bases=(shewrote.models.EasyAuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkCirculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.circulation')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shewrote.receptiontype')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.work')),
            ],
        ),
        migrations.CreateModel(
            name='PersonCirculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.circulation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shewrote.receptiontype')),
            ],
        ),
        migrations.CreateModel(
            name='EditionCirculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.circulation')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.edition')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shewrote.receptiontype')),
            ],
        ),
        migrations.AddField(
            model_name='circulation',
            name='received_editions',
            field=models.ManyToManyField(through='shewrote.EditionCirculation', to='shewrote.edition'),
        ),
        migrations.AddField(
            model_name='circulation',
            name='received_persons',
            field=models.ManyToManyField(through='shewrote.PersonCirculation', to='shewrote.person'),
        ),
        migrations.AddField(
            model_name='circulation',
            name='received_works',
            field=models.ManyToManyField(through='shewrote.WorkCirculation', to='shewrote.work'),
        ),
        migrations.AddIndex(
            model_name='circulation',
            index=models.Index(fields=['title'], name='shewrote_ci_title_a01036_idx'),
        ),
        migrations.AddIndex(
            model_name='circulation',
            index=models.Index(fields=['date_of_reception'], name='shewrote_ci_date_of_1f56f1_idx'),
        ),
    ]
