# Generated by Django 4.2.5 on 2025-06-04 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0055_alter_reception_is_same_as_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_country',
            field=models.BooleanField(default=False),
        ),
    ]
