# Generated by Django 4.2.5 on 2025-05-27 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0055_alter_reception_is_same_as_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edition',
            old_name='publication_year',
            new_name='publication_year_start',
        ),
        migrations.AddField(
            model_name='edition',
            name='publication_year_end',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
