# Generated by Django 4.2.5 on 2025-05-14 13:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0056_circulation_workcirculation_personcirculation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CirculationSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_title', models.TextField()),
                ('year_of_publication', models.CharField(max_length=50)),
                ('shelf_mark', models.CharField(blank=True, max_length=128)),
                ('url', models.URLField(blank=True)),
                ('country_of_publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shewrote.country')),
            ],
        ),
        migrations.CreateModel(
            name='CirculationSourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='PersonCirculationSourceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='PersonCirculationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulation_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.circulationsource')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shewrote.personcirculationsourcerole')),
            ],
        ),
        migrations.AddField(
            model_name='circulationsource',
            name='related_persons',
            field=models.ManyToManyField(through='shewrote.PersonCirculationSource', to='shewrote.person'),
        ),
        migrations.AddField(
            model_name='circulationsource',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shewrote.circulationsourcetype'),
        ),
        migrations.AddField(
            model_name='circulation',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shewrote.circulationsource'),
        ),
    ]
