# Generated by Django 4.2.5 on 2025-05-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0057_circulationsource_circulationsourcetype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circulation',
            old_name='quotation_reception',
            new_name='quotation',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='quotation_reception',
            new_name='quotation',
        ),
        migrations.RemoveField(
            model_name='circulation',
            name='part_of_work',
        ),
    ]
