# Generated by Django 4.2.5 on 2025-06-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0056_place_is_country_alter_reception_part_of_work'),
        ('shewrote', '0058_rename_quotation_reception_circulation_quotation_and_more'),
    ]

    operations = [
    ]
