# Generated by Django 4.2.5 on 2025-06-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0056_rename_publication_year_edition_publication_year_start_and_more'),
        ('shewrote', '0059_merge_20250604_1252'),
    ]

    operations = [
    ]
