# Generated by Django 4.2.5 on 2025-06-11 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0060_merge_20250605_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='part_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contained_receptions', to='shewrote.work'),
        ),
    ]
