# Generated by Django 4.2.5 on 2026-01-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0061_alter_reception_part_of_work'),
    ]

    operations = [
        migrations.RunSQL(sql="CREATE EXTENSION unaccent", reverse_sql="DROP EXTENSION IF EXISTS unaccent"),
        migrations.RunSQL(sql="GRANT EXECUTE ON FUNCTION unaccent(text) TO django_app_pg_user",
                          reverse_sql="REVOKE EXECUTE ON FUNCTION unaccent(text) FROM django_app_pg_user"),
    ]
