# Generated by Django 4.2.5 on 2025-11-20 08:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0061_alter_reception_part_of_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cerl', models.CharField(blank=True, max_length=255)),
                ('start_of_activity', models.IntegerField(blank=True, null=True)),
                ('end_of_activity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublisherPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.person')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shewrote.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='publisher',
            name='persons',
            field=models.ManyToManyField(blank=True, through='shewrote.PublisherPerson', to='shewrote.person'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='place_of_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shewrote.place'),
        ),
        migrations.AddField(
            model_name='edition',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shewrote.publisher'),
        ),
    ]
