# Generated by Django 4.2.5 on 2025-11-20 08:45
import re
from django.db import migrations


def populate_publisher(apps, schema_editor):
    Publisher = apps.get_model('shewrote', 'Publisher')
    Edition = apps.get_model('shewrote', 'Edition')

    for edition in Edition.objects.all():
        publisher = Publisher()
        cerl_publisher = edition.cerl_publisher
        publisher.name = cerl_publisher
        if re.match(r'^(https?://data.cerl.org/thesaurus/)|(cn.\d{8})', cerl_publisher):
            publisher.cerl = cerl_publisher
        publisher.save()
        publisher.persons.add(*(edition.related_persons.all()))
        edition.publisher = publisher
        edition.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0062_publisher_publisherperson_publisher_persons_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_publisher),
    ]
