# Generated by Django 4.2.5 on 2026-05-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0062_auto_20260120_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='person',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='place',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
