# Generated by Django 4.2.5 on 2026-06-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0063_country_wikidata_id_person_wikidata_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='reception_count',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='reception_count_incl_works',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
