# Generated by Django 4.2.5 on 2025-11-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0063_auto_20251120_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='cerl_publisher',
        ),
    ]
