# Generated by Django 4.2.5 on 2026-06-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0064_person_reception_count_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['short_name'], name='shewrote_pe_short_n_758258_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['reception_count'], name='shewrote_pe_recepti_797f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['reception_count_incl_works'], name='shewrote_pe_recepti_fdb1b3_idx'),
        ),
    ]
