# Generated by Django 4.2.5 on 2026-06-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0065_person_shewrote_pe_short_n_758258_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='reception_count',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
