# Generated by Django 4.2.5 on 2026-06-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0066_work_reception_count'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='person',
            name='shewrote_pe_normali_6b613d_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='shewrote_pe_normali_9416bc_idx',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='normalised_date_of_birth',
            new_name='normalised_year_of_birth',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='normalised_date_of_death',
            new_name='normalised_year_of_death',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='date_of_birth',
            new_name='year_of_birth',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='date_of_death',
            new_name='year_of_death',
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['normalised_year_of_birth'], name='shewrote_pe_normali_b21c45_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['normalised_year_of_death'], name='shewrote_pe_normali_b97087_idx'),
        ),
    ]
