# Generated by Django 4.2.5 on 2026-09-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0067_remove_person_shewrote_pe_normali_6b613d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulation',
            name='editing_notes_file',
            field=models.FileField(blank=True, null=True, upload_to='editingnotes/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='collective',
            name='editing_notes_file',
            field=models.FileField(blank=True, null=True, upload_to='editingnotes/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='edition',
            name='editing_notes_file',
            field=models.FileField(blank=True, null=True, upload_to='editingnotes/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='person',
            name='editing_notes_file',
            field=models.FileField(blank=True, null=True, upload_to='editingnotes/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='reception',
            name='editing_notes_file',
            field=models.FileField(blank=True, null=True, upload_to='editingnotes/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='work',
            name='editing_notes_file',
            field=models.FileField(blank=True, null=True, upload_to='editingnotes/%Y/%m/%d'),
        ),
    ]
