# Generated by Django 4.2.5 on 2026-09-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shewrote', '0068_person_editing_notes_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_locked_flag',
            field=models.BooleanField(default=False),
        ),
    ]
